INSERT INTO UNIVERSIDAD (NOMBRE) VALUES('UNIDADES TECNOLOGICAS DE SANTANDER')

INSERT INTO ESTUDIANTES (NOMBRE,UNIVERSIDAD_ID) VALUES('Camilo Ernesto Rodriguez',1);
INSERT INTO ESTUDIANTES (NOMBRE,UNIVERSIDAD_ID) VALUES('Andres Julian Nieto',1);
INSERT INTO ESTUDIANTES (NOMBRE,UNIVERSIDAD_ID) VALUES('Diego Fernando Rangel',1);
INSERT INTO ESTUDIANTES (NOMBRE,UNIVERSIDAD_ID) VALUES('Diana Milena Tarazona',1);

